### ISSUE TITLE
useFind returns the same item multiple times

### ISSUE THREAD

**Issue by johnayoung** [humaans/figbird#1]
Hi All,

First off, great library! I was going to build out something similar until I came upon this. Thanks for saving me a bunch of time.

When using the useFind hook, It seems to return the first result for every result. Here is what I am using:

`
 const { loading, error, data } = useFind('templates', {
    query: {},
  });
`

Result in component: The first result repeated 5 times.

Result verified in websocket return : Correct.

Any idea what may be causing this?

**Comment by KidkArolis** [comment]
First thought, does your data have id field? If its not called “id” or “_id” you might have to configure the idField option.

**Comment by johnayoung** [comment]
@KidkArolis That was definitely it! Now I have a different problem...

We use SQL relations, and have named the IDs in our table based on the resource...for example:

1. Table name: 'users', id: 'userId'
2. Table name: 'providers', id: 'providerId'

Can you think of a workaround where we could have dynamic ids?

**Comment by KidkArolis** [comment]
Ah, sorry, missed this GitHub notification.

`idField` can be a function, for example: `item => item.userId || item.providerId`.

I'm wondering if I should also pass `serviceName` to `idField(item, serviceName)`

**Comment by KidkArolis** [comment]
The latest version logs a warning if ID is missing to help catch this case.

If the dynamic ID issue is still relevant, please reopen as a new issue and we can get that implemented.
