### ISSUE TITLE
Example incomplete

### ISSUE THREAD

**Issue by lemlich** [humaans/figbird#7]
I was unable to figure out how to use figbird because the example was incomplete. It doesn't include the client configuration module.  Here's what the code should look like, according to David Luecke
```
import React, {useState} from 'react';
import {Provider} from 'figbird';
**import client from './feathers';**
import Users from './Notes.js';

function App() {
    return (
        <Provider feathers={**client**}>
            <Notes/>
        </Provider>
    )
}
export default App;
```

Note that, in this example, the module in ./feathers contains the feathers configuration (URL, socket, etc.). In the current example, it would be impossible to specify a different port.

**Comment by lemlich** [comment]
Sorry. I don't know how to put the body of the code in, but the Provider feathers argument should be 
**client**. I don't know how to put a link into the discussion , but search for figbird in the feathers slack channel to see what this is about.

**Comment by joeinnes** [comment]
I was also a bit confused by the documentation on this, and the example didn't seem to work.

Basically, you need to pass a configured client. You can do this in a separate module, or using something like the below:

```
import React, { useState } from 'react'
import io from 'socket.io-client'
import feathers from '@feathersjs/client'
import { Provider, useFind } from 'figbird'

const socket = io('http://localhost:3030')
const client = feathers()

client.configure(feathers.socketio(socket))
client.configure(feathers.authentication({
  storage: window.localStorage
}))

function App() {
  return (
    <Provider feathers={client}>
      <Notes />
    </Provider>
  )
}

function Notes({ tag }) {
  const { status, data, total } = useFind('notes', { query: { tag } })

  if (status === 'loading') {
    return 'Loading...'
  } else if (status === 'error') {
    return notes.error.message
  }

  return (
    <div>
      Showing {data.length} notes of {total}
    </div>
  )
}
```

I'll create a PR for this in case anyone's interested, but it may not really be required.
